server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://system-center:8000/eureka/
spring:
  application:
    name: system-gateway
logging:
  level:
    site.rhys.forum.service.auth: info
zuul:
  routes:
    service-user:
      serviceId: service-user
      path: /${zuul.routes.service-user.serviceId}/**
    service-article:
      serviceId: service-article
      path: /${zuul.routes.service-article.serviceId}/**
