server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: system-gateway
  sleuth:
    sampler:
      percentage: 1
    enabled: true
  zipkin:
    base-url: http://system-zipkin/
    sender:
      type: web
logging:
  level:
    site.rhys.forum.service.auth: info
zuul:
  routes:
    service-auth:
      serviceId: service-auth
      path: /${zuul.routes.service-auth.serviceId}/**
    service-user:
      serviceId: service-user
      path: /${zuul.routes.service-user.serviceId}/**
    service-article:
      serviceId: service-article
      path: /${zuul.routes.service-article.serviceId}/**
feign:
  hystrix:
    enabled: true


