version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
    ports:
      - "3306:3306"
    volumes:
      - "~/docker/mysql:/var/lib/mysql"
  system-center:
    container_name: system-center
    image: forum-server/forum-system-center:1.0.0
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8000:8000"
  system-gateway:
    container_name: system-gateway
    image: forum-server/forum-system-gateway:1.0.0
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8001:8000"
  service-user:
    container_name: controller-user
    image: forum-server/forum-controller-user:1.0.0
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8002:8000"
  service-article:
    container_name: controller-article
    image: forum-server/forum-controller-article:1.0.0
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8003:8000"