server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://system-center:8000/eureka/
spring:
  application:
    name: service-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql:3306/forum?characterEncoding=utf-8
      initial-size: 1
      max-active: 10
      min-idle: 1
      max-wait: 60000
      filters: stat,wall,log4j,config
      stat-view-servlet:
        reset-enable: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    site.rhys.forum.service.user: info
feign:
  hystrix:
    enabled: true
