spring:
  application:
    name: forum-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RhysXia/forum-server
          search-paths:
            - config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8200

