spring:
  application:
    name: forum-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RhysXia/forum-server
          search-paths: config/{profile}
server:
  port: 8200

