eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8100
zuul:
  routes:
    bus:
      path: /bus/**
      serviceId: forum-bus
    config:
      path: /config/**
      serviceId: forum-config
    service-user:
      path: /service/user/**
      serviceId: forum-service-user

