eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 9100
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf-8
      initial-size: 1
      max-active: 10
      min-idle: 1
      max-wait: 60000
      filters: stat,wall,log4j,config
      stat-view-servlet:
        reset-enable: false
logging:
  level:
    site.rhys.forum.service.auth: info
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: site.rhys.forum.common.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true