server:
  port: 9020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: service-article
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf-8
      initial-size: 1
      max-active: 10
      min-idle: 1
      max-wait: 60000
      filters: stat,wall,log4j,config
      stat-view-servlet:
        reset-enable: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sleuth:
    sampler:
      percentage: 1
    enabled: true
  zipkin:
    base-url: http://system-zipkin/
    sender:
      type: web
logging:
  level:
    site.rhys.forum.service.article: info
feign:
  hystrix:
    enabled: true