server:
  port: 8020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: system-zipkin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf-8
      initial-size: 1
      max-active: 10
      min-idle: 1
      max-wait: 60000
      filters: stat,wall,log4j,config
      stat-view-servlet:
        reset-enable: false
#    schema: classpath:zipkin.sql
logging:
  level:
    site.rhys.forum.service.auth: info
feign:
  hystrix:
    enabled: true
zipkin:
  storage:
    type: mysql
    mysql:
      host: localhost
      port: 3306
      username: root
      password: root
      db: forum

