server:
  port: 8000
spring:
  application:
    name: system-center
  sleuth:
    sampler:
      percentage: 1
    enabled: true
  zipkin:
    base-url: http://system-zipkin/
    sender:
      type: web
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
management:
  security:
    enabled: false